# Generated by Django 3.0.1 on 2019-12-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='questions',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
